name: CI Build

on:
  pull_request:
    branches: [ main ]
  push:
    branches-ignore: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Validate workspace files
        run: |
          ls -la
          test -f index.html
      - name: Echo build summary
        run: echo "Static app validated. No build step required."

