name: Firebase Hosting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: write

jobs:
  deploy:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate env.js for client
        run: |
          cat > env.js << 'EOF'
          window.ENV = {
            apiKey: "${{ vars.FIREBASE_API_KEY }}",
            authDomain: "${{ vars.FIREBASE_AUTH_DOMAIN }}",
            projectId: "${{ vars.FIREBASE_PROJECT_ID }}",
            storageBucket: "${{ vars.FIREBASE_STORAGE_BUCKET }}",
            messagingSenderId: "${{ vars.FIREBASE_MESSAGING_SENDER_ID }}",
            appId: "${{ vars.FIREBASE_APP_ID }}",
            measurementId: "${{ vars.FIREBASE_MEASUREMENT_ID }}"
          };
          EOF

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          projectId: horus-vision-4587f
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

